DROP TABLE IF EXISTS jokes;
DROP TABLE IF EXISTS categories;

CREATE TABLE IF NOT EXISTS categories (
  _id INTEGER PRIMARY KEY NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS jokes (
  _id INTEGER PRIMARY KEY NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  text TEXT NOT NULL DEFAULT '',
  upvotes INT DEFAULT '0',
  downvotes INT DEFAULT '0'
);

CREATE TABLE jokes_categories (
    _id INTEGER PRIMARY KEY NOT NULL,
    joke_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    FOREIGN KEY(joke_id) REFERENCES jokes(_id),
    FOREIGN KEY(category_id) REFERENCES categories(_id)
);

